language: generic

before-install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs

services:
  - docker

matrix:
env:
  # - JDKVER=jdk7
  - JDKVER=jdk8

# This is essential lest the script is ignored and Travis just runs gradle.
install: true

before-script:
- docker pull mdernst/ubuntu-for-cf-$JDKVER

script:
- REMOTE_ORIGIN_URL=`git config --get remote.origin.url`
- echo "JDKVER=${JDKVER}"
- echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
- echo "REMOTE_ORIGIN_URL=${REMOTE_ORIGIN_URL}"
- echo "TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE}"
- echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}"
- echo "TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}"
- >-
  docker run mdernst/ubuntu-for-cf-$JDKVER /bin/bash -c "true &&
     export JAVA_HOME=\`which javac|xargs readlink -f|xargs dirname|xargs dirname\` &&
     if [ $TRAVIS_EVENT_TYPE = pull_request ] ; then
       git clone --quiet --depth 9 $REMOTE_ORIGIN_URL $TRAVIS_BUILD_DIR/checker-framework-inference
       cd $TRAVIS_BUILD_DIR/checker-framework-inference
       git fetch origin +refs/pull/$TRAVIS_PULL_REQUEST/merge
       git checkout -qf FETCH_HEAD
       git config user.email noone@cares.com
       git config user.name Noone Cares
       git remote add theupstream https://github.com/$TRAVIS_REPO_SLUG.git
       git pull --depth 9 theupstream $TRAVIS_BRANCH
     else
       git clone --quiet -b $TRAVIS_BRANCH --depth 9 $REMOTE_ORIGIN_URL $TRAVIS_BUILD_DIR/checker-framework-inference
       cd $TRAVIS_BUILD_DIR/checker-framework-inference checker-framework-inference
     fi &&
     java -version &&
     javac -version &&
     export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8 &&
     export TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG &&
     export TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR &&
     ./.travis-build.sh"

sudo: false

after-script:
- |
    set +e
    declare exitCode;
    curl -sSL https://raw.githubusercontent.com/mernst/travis-after-all/master/lib/travis-after-all.js | tac | tac | nodejs
    exitCode=$?
    echo "exitCode=$exitCode TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"

# TODO: add down-stream project travis tests

git:
  depth: 9
